# Generated by Django 5.2.8 on 2026-04-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('tv', 'TV')], default='mobile', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('price', models.IntegerField()),
                ('ram', models.IntegerField(blank=True, help_text='RAM in GB', null=True)),
                ('storage', models.IntegerField(blank=True, help_text='Storage in GB', null=True)),
                ('battery', models.IntegerField(blank=True, help_text='Battery in mAh', null=True)),
                ('camera', models.IntegerField(blank=True, help_text='Main Camera in MP', null=True)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('buy_url', models.URLField(blank=True, help_text='Store link yahan daalein', max_length=500, null=True)),
                ('store_name', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('reliance', 'Reliance Digital'), ('other', 'Other Store')], default='amazon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phones.brand')),
            ],
        ),
    ]
